swagger: '2.0'
info:
  version: 1.0.0
  title: Simple API
  description: Learning Swagger
host: rest.nexmo.com
basePath: /sms
schemes:
  - https
paths:
  /json:
    post:
      summary: Send SMS Message to your recipient
      produces:
        - application/json
      consumes:
        - application/x-www-form-urlencoded
      operationId: Send SMS with OTP Code
      parameters:
        - in: formData
          name: api_key
          type: string
          description: API Key
        - in: formData
          name: api_secret
          type: string
          description: API Secret Key
        - in: formData
          name: to
          type: string
          description: SMS Recipient
        - in: formData
          name: from
          type: string
          description: From Number
        - in: formData
          name: text
          type: string
          description: Message to send
          
      responses:
        '200':
          description: Successfull Response
          schema:
            $ref: '#/definitions/returnvalue'

        
definitions:
      
  returnvalue:
    type: object
    properties:
      request_id:
        type: string
      status:
        type: string
