swagger: '2.0'
info:
  version: 1.0.0
  title: Simple API
  description: Learning Swagger
securityDefinitions:
  basicAuth:
    type: basic
    
host: api.stripe.com
basePath: /v1
schemes:
  - https
security:
  - basicAuth: []
paths:
  /charges:
    post:
      summary: Trigger Transactional Message
      
      
      produces:
        - application/json
      consumes:
        - application/x-www-form-urlencoded
      operationId: Trigger Transactional Message
      parameters:
        - in: formData
          name: currency
          type: string
          description: Currency to be charged
        - in: formData
          name: amount
          type: integer
          description: amount to be charged
        - in: formData
          name: source
          type: string
          description: Source of charge
        - in: formData
          name: description
          type: string
          description: Charge Description
          
      responses:
        '200':
          description: Successfull Response
          schema:
            $ref: '#/definitions/returnvalue'
        '400':
          description: Status Declines
          schema:
            $ref: '#/definitions/error'
definitions:
  errorMessage:
    type: object
    properties:
      message:
        type: string
 
  error:
    type: object
    $ref: '#/definitions/errorMessage'
      
  returnvalue:
    type: object
    properties:
      id:
        type: string
      status:
        type: string
